### ISSUE TITLE
データベースのテーブルの作成, 変更がうまくいかない

### ISSUE THREAD

**Issue by SgKnt** [itsp-pbl-2023/tonkatsu#10]
コンテナを立てた時に`/docker-entrypoint-initdb.d`内にあるファイルが読み込まれてテーブルの作成等が行われるはずなのにうまくいかない.

**Comment by SgKnt** [comment]
やっぱり`/var/lib/mysql`をホスト側の`server/db/data`に置いて永続化している(バインドマウントというらしい)のがダメっぽいので, volumeを作ってそこに永続化するようにしました. #11 
これでテーブル作成してみてください @ShimboAkito

**Comment by ShimboAkito** [comment]
感謝😊
あとで確認します

**Comment by SgKnt** [comment]
できた
