### ISSUE TITLE
OpenAPIのスキーマの修正

### ISSUE THREAD

**Issue by SgKnt** [itsp-pbl-2023/tonkatsu#12]
URLパラメータ渡しになっているので修正

**Comment by SgKnt** [comment]
クライアント側から`/account` `/login`にリクエストを送るときのリクエストボディが`userID=foo&password=bar`みたいになっていると思うんですが, スキーマを修正したのでそれに合わせてjson形式で送るよう変更してもらってもいいですか?
@Nanashima21 @morinoyu8

**Comment by morinoyu8** [comment]
json形式で送るように変更しました
間違っていれば教えてください🙇
