### ISSUE TITLE
WebSocket の部屋に入っているユーザーをリストで欲しい

### ISSUE THREAD

**Issue by morinoyu8** [itsp-pbl-2023/tonkatsu#26]
新しく部屋に入ったユーザーがそれまでに部屋に入っているユーザーを取得できない.
新しく入るユーザーにだけリストを渡すか, 全員に部屋に入っているすべてのユーザのリストを送るのもあり？

**Comment by SgKnt** [comment]
「全員に部屋に入っているすべてのユーザのリストを送る」API決めよう
