### ISSUE TITLE
最終結果

### ISSUE THREAD

**Issue by SgKnt** [itsp-pbl-2023/tonkatsu#70]
今のバックエンドの実装だと一番最後の質問者しか最終結果画面に移行する権限を持ってなくて，みんな同時に最終結果画面に行っちゃうので，`"game_finish_game"`コマンドを全員から受け付けるようにして個別に`"game_show_all_result"`を送るようにする?

**Comment by ShimboAkito** [comment]
そのほうがいいかも

**Comment by morinoyu8** [comment]
わちゃわちゃ盛り上がるのがいいなら全員同時に最終結果見れた方がいいかも？

**Comment by SgKnt** [comment]
パチンコエフェクト忘れてた...
そのままでいいか
